import { Inter } from "next/font/google";
import "./globals.css";
import NavBar from "./NavBar";
import AppBar from "./AppBar";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <main className="w-screen h-screen flex ">
          <NavBar />
          <AppBar />
          <div className="p-4 w-full h-full">{children}</div>
        </main>
      </body>
    </html>
  );
}
