// import { Inter } from "next/font/google";
// import "./globals.css";
// import NavBar from "./NavBar";
// import AppBar from "./AppBar";

// const inter = Inter({ subsets: ["latin"] });

// export const metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

// export default function RootLayout({ children }) {
//   return (
//     <html lang="en">
//       <body className={inter.className}>
//         <main className="w-screen h-screen flex ">
//           <NavBar />
//           <AppBar />
//           <div className="p-4 w-full h-full">{children}</div>
//         </main>
//       </body>
//     </html>
//   );
// }
import React from "react";
import NavBar from "../NavBar";
import Header from "../AppBar";

const DashboardLayout = ({ children }) => {
  return (
    <div className="flex h-screen bg-gray-100">
      <div className="w-64 bg-gray-100 text-white">
        <NavBar />
      </div>
      <div className="flex flex-col flex-1 overflow-hidden">
        <Header />
        <main className="flex-1 overflow-x-hidden overflow-y-auto bg-gray-200 p-6">
          {children}
        </main>
      </div>
    </div>
  );
};

export default DashboardLayout;
